import Head from "next/head";
import React, { useState } from "react";
import { Button } from "../components/Button";
import { Htag } from "../components/Htag";
import { Paragraph } from "../components/Paragraph";
import { Rating } from "../components/Rating";
import { Star } from "../components/icon-components/Star";
import { Tag } from "../components/Tag";
import { Layout, WithLayout } from "../layout/inedx";

const Home = (): JSX.Element => {
  const [counter, setCounter] = useState<number>(0);
  const [rating, setRating] = useState(4);

  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Main
    </>
  );
};

export default WithLayout(Home);
