import Head from "next/head";
import React from "react";
import { WithLayout } from "../layout";
import { GetStaticProps } from "next";
import axios from "axios";

const Home: React.FC<IHomeProps> = ({ menu }) => {
  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default WithLayout(Home);

export const getStaticProps: GetStaticProps<IHomeProps> = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<IMenuItem[]>(
    `${process.env.NEXT_PUBLIC_API}`,
    {
      firstCategory,
    }
  );
  return {
    props: {
      menu,
      firstCategory,
    },
  };
};

interface PageItem {
  alias: string;
  title: string;
  _id: string;
  category: string;
}

interface IMenuItem {
  _id: {
    secondCategory: string;
  };
  pages: PageItem[];
}

interface IHomeProps extends Record<string, unknown> {
  menu?: IMenuItem[];
  firstCategory?: number;
}
