import Head from "next/head";
import React from "react";
import { GetStaticProps } from "next";
import axios from "axios";
import { WithLayout } from "../../layout";

const Course: React.FC<ICourseProps> = ({ menu }) => {
  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {menu.map((el) => (
          <li key={el._id.secondCategory}>{el._id.secondCategory}</li>
        ))}
      </ul>
    </>
  );
};

export default WithLayout(Course);

export const getStaticProps: GetStaticProps<ICourseProps> = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<MenuItem[]>(
    `${process.env.NEXT_PUBLIC_API}`,
    {
      firstCategory,
    }
  );
  return {
    props: {
      menu,
      firstCategory,
    },
  };
};

interface PageItem {
  alias: string;
  title: string;
  _id: string;
  category: string;
}

interface MenuItem {
  _id: {
    secondCategory: string;
  };
  pages: PageItem[];
}

interface ICourseProps extends Record<string, unknown> {
  menu: MenuItem[];
  firstCategory: number;
}
